version: 2
models:

  - name: fact_order_items
    description: "Central fact table containing order item transactions with foreign keys to dimension tables"
    columns:
      - name: order_item_id
        description: "Unique identifier for each order item (Primary Key)"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Foreign key to orders"
        tests:
          - not_null
      - name: product_id
        description: "Foreign key to dim_products"
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_id
      - name: seller_id
        description: "Foreign key to dim_sellers"
        tests:
          - not_null
          - relationships:
              to: ref('dim_sellers')
              field: seller_id
      - name: customer_id
        description: "Foreign key to dim_customers"
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_id
      - name: order_date_key
        description: "Foreign key to dim_orders (date dimension)"
        tests:
          - not_null
          - relationships:
              to: ref('dim_orders')
              field: date_key
      - name: payment_type_key
        description: "Foreign key to dim_payments (-1 for unknown)"
        tests:
          - not_null
          - relationships:
              to: ref('dim_payments')
              field: payment_type_key
      - name: price
        description: "Item price in local currency"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
      - name: freight_value
        description: "Shipping cost for the item"
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: numeric
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
      - name: review_score
        description: "Customer review score (1-5)"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 1
              max_value: 5
      - name: delivery_time_days
        description: "Days between order purchase and delivery"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 365

  - name: dim_products
    description: "Product dimension containing product attributes"
    columns:
      - name: product_id
        description: "Unique product identifier (Primary Key)"
        tests:
          - unique
          - not_null

  - name: dim_customers
    description: "Customer dimension with geographic information"
    columns:
      - name: customer_id
        description: "Unique customer identifier (Primary Key)"
        tests:
          - unique
          - not_null
      - name: geolocation_id
        description: "Foreign key to dim_geolocation"
        tests:
          - relationships:
              to: ref('dim_geolocation')
              field: geolocation_id

  - name: dim_sellers
    description: "Seller dimension with geographic information"
    columns:
      - name: seller_id
        description: "Unique seller identifier (Primary Key)"
        tests:
          - unique
          - not_null
      - name: geolocation_id
        description: "Foreign key to dim_geolocation"
        tests:
          - relationships:
              to: ref('dim_geolocation')
              field: geolocation_id

  - name: dim_geolocation
    description: "Geographic dimension for customers and sellers"
    columns:
      - name: geolocation_id
        description: "Unique geographic location identifier (Primary Key)"
        tests:
          - unique
          - not_null
      - name: geolocation_zip_code_prefix
        description: "ZIP code prefix"
      - name: latitude
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: -90
              max_value: 90
      - name: longitude
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: -180
              max_value: 180

  - name: dim_dates
    description: "Date dimension for order analysis"
    columns:
      - name: date_key
        description: "Date key (Primary Key)"
        tests:
          - unique
          - not_null
      - name: day_of_week
        tests:
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]
      - name: month_name
        tests:
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ["January","February","March","April","May","June","July","August","September","October","November","December"]

  - name: dim_payments
    description: "Payment type dimension"
    columns:
      - name: payment_type_key
        description: "Unique payment type key (Primary Key)"
        tests:
          - unique
          - not_null
      - name: payment_type
        tests:
          - dbt_expectations.expect_column_values_to_be_in_set:
              value_set: ["credit_card","debit_card","boleto","voucher","not_defined"]
