version: 1
default_environment: dev
project_id: eed08545-8f1e-4497-bb7a-7d3d30ec8fdf
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
    config:
      files:
      - entity: order_item
        path: ../assets/olist_order_items_dataset.csv
        keys: [order_item_id]

      flattening_enabled: true
      flattening_max_depth: 1
  loaders:
  - name: target-bigquery
    variant: z3z1ma
    pip_url: git+https://github.com/z3z1ma/target-bigquery.git
    config:
      project: sound-vehicle-468314-q4
      dataset: m2_ingestion
      credentials_path: 
        /Users/alexfoo/Documents/NTU_DSAI/sound-vehicle-468314-q4-c77615633d50.json
      method: batch_job
      denormalized: true
      flattening_enabled: true
      flattening_max_depth: 1
      batch_size: 5000
